name: Python Script Automation

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every five minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 
        
    - name: Install Dependencies
      run: pip install -r requirements.txt 
      
    - name: Run Python Script
      run: python meditationsPassages.py
